# Generated by Django 2.0.5 on 2018-06-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20180630_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcegraph',
            name='faceted_search',
            field=models.ManyToManyField(to='pages.Property'),
        ),
    ]
