# Generated by Django 2.0.5 on 2018-07-05 13:56

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0018_auto_20180701_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timelinegraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
                ('source', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, editable=False, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('date_marked', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='domain_subject', chained_model_field='domain_subject', on_delete=django.db.models.deletion.CASCADE, related_name='date_marked', to='pages.Property')),
                ('domain_subject', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='repository_query', chained_model_field='repository_query', on_delete=django.db.models.deletion.CASCADE, to='pages.Domain')),
                ('faceted_search', models.ManyToManyField(to='pages.Property')),
                ('repository_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Repository')),
            ],
        ),
    ]
