# Generated by Django 2.0.5 on 2018-07-05 14:10

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20180705_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelinegraph',
            name='date_marked',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='domain_subject', chained_model_field='domain_prop', on_delete=django.db.models.deletion.CASCADE, related_name='date_marked', to='pages.Property'),
        ),
    ]
